if (NOT DEFINED GCOV_PATH)
    message(FATAL_ERROR "GCOV_PATH is not defined. Pass -DGCOV_PATH=<path to gcov> when invoking this script.")
endif()

if (NOT DEFINED BINARY_DIR)
    message(FATAL_ERROR "BINARY_DIR is not defined. Pass -DBINARY_DIR=<build directory> when invoking this script.")
endif()

if (NOT DEFINED REPORT_PATH)
    message(FATAL_ERROR "REPORT_PATH is not defined. Pass -DREPORT_PATH=<report file> when invoking this script.")
endif()

file(GLOB_RECURSE GCDA_FILES "${BINARY_DIR}/*.gcda")
if (GCDA_FILES STREQUAL "")
    message(FATAL_ERROR "No .gcda files found in ${BINARY_DIR}. Make sure the unit tests ran before collecting coverage.")
endif()

file(WRITE "${REPORT_PATH}" "# Branch coverage report generated by RunBranchCoverage.cmake\n")

set(GCDA_DIRS)
foreach(gcda IN LISTS GCDA_FILES)
    get_filename_component(dir "${gcda}" DIRECTORY)
    list(APPEND GCDA_DIRS "${dir}")
endforeach()
list(REMOVE_DUPLICATES GCDA_DIRS)

foreach(dir IN LISTS GCDA_DIRS)
    file(GLOB DIR_GCDA "${dir}/*.gcda")
    if (DIR_GCDA)
        execute_process(
                COMMAND "${GCOV_PATH}" -b -o "${dir}" ${DIR_GCDA}
                WORKING_DIRECTORY "${dir}"
                RESULT_VARIABLE gcov_result
                OUTPUT_VARIABLE gcov_stdout
                ERROR_VARIABLE gcov_stderr
        )
        if (NOT gcov_result EQUAL 0)
            message(FATAL_ERROR "gcov failed in directory ${dir}: ${gcov_stderr}")
        endif()
        file(APPEND "${REPORT_PATH}" "=== ${dir} ===\n${gcov_stdout}\n${gcov_stderr}\n")
    endif()
endforeach()

message(STATUS "Branch coverage report saved to ${REPORT_PATH}")
